import Header from "./components/Header";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        <main
          className="flex flex-row bg-gray-200 text-gray-800
          dark:bg-slate-900 dark:text-white text-center text-2xl font-bold shadow-md pt-8"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
