import DashBoard from './components/DashBoard'

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AIImage Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashBoard>
          {children}
        </DashBoard>
      </body>
    </html>
  )
}
